# Generated by Django 3.1.4 on 2021-04-03 12:06

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_title',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
